### ISSUE TITLE
Build Tools

### ISSUE THREAD

**Issue by Trass3r** [Farwaykorse/VS_Clang#1]
Does it also work if only the Build Tools are installed?
I remember with vswhere small changes may be required in comparison to a full VS installation.
`vswhere -latest -products * -requires Microsoft.Component.MSBuild`

**Comment by Farwaykorse** [comment]
Data for a bare Build Tools 2017 install is returned when the flag `-all` is used.

To prevent additional future 'renaming' issues, I decided to just return the install location of every (non legacy) version of VS.
The exact bundles/components installed I believe not to be relevant. At least not for the current scope of the integration.
For the current purpose we can rely on a the directory checks to determine if relevant toolset implementations are present. These directories have to be found in any case.

If you run into an issue with the Build Tools, please let me know.
